### ISSUE TITLE
How this matrix is generated

### ISSUE THREAD

**Issue by qianyizhaoooo** [JiamanZhang/Lab_ABcompartment#1]
Dear author:
I am referring to your method of identifying A /B compartment regions in the literature, then I see that you have constructed the interaction matrix with juicer and identified A /B compartment  regions using this matrix, but I do not understand how this was generated  the input file you used in R as follow:
https://github.com/JiamanZhang/Lab_ABcompartment/blob/main/demos/20kPC1/input/chr18.0_5M.20k.oe.matrix
, I want to know if this matrix is generated by juicer  can you tell me what method was used, I would appreciate it if you could tell me the method or command to use.
I am looking forward to your reply.
Thanks

**Comment by JiamanZhang** [comment]
OK. It's no problem that the observed/expected contacts matrices were generated using Juicer at different resolution.

**Comment by ZQY19960810** [comment]
Thank you very much! So I got your this matrix is oe contacts matrix , but maybe I missed some information,I didn't find a well method in juicer to covert .hic to this format matrix.  would you give some more details about the method ? I will so appreciate for it

**Comment by JiamanZhang** [comment]
Hi. You can use JUICER TOOLS to generate oe matrices (https://aidenlab.org/documentation.html).

**Comment by JiamanZhang** [comment]
java -Xmx20g -jar juicer_tools.1.8.9_jcuda.0.8.jar dump 
Usage:   juicer_tools dump <observed/oe> <NONE/VC/VC_SQRT/KR> <hicFile(s)> <chr1>[:x1:x2] <chr2>[:y1:y2] <BP/FRAG> <binsize> [outfile]
	dump <norm/expected> <NONE/VC/VC_SQRT/KR> <hicFile(s)> <chr> <BP/FRAG> <binsize> [outfile]
	dump <loops/domains> <hicFile URL> [outfile]
